
- name: snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present

- name: snapd is started
  ansible.builtin.service:
    name: snapd
    state: started

- name: Ensure microk8s is installed
  community.general.snap:
    name: microk8s
    classic: yes
    state: present

- name: Check MicroK8s status
  command: microk8s status --wait-ready
  register: microk8s_status
  changed_when: False
  failed_when: False

- name: Start MicroK8s if it is not running
  command: microk8s start
  when: "'microk8s is not running' in microk8s_status.stdout"
  notify: wait_for_microk8s