
- name: snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present

- name: snapd is started
  ansible.builtin.service:
    name: snapd
    state: started

- name: Ensure microk8s is installed
  community.general.snap:
    name: microk8s
    classic: yes
    state: present

- name: Check MicroK8s status
  command: microk8s status --wait-ready
  register: microk8s_status
  changed_when: False
  failed_when: False

- name: Start MicroK8s if it is not running
  command: microk8s start
  when: "'microk8s is not running' in microk8s_status.stdout"
  notify: wait_for_microk8s

- name: Deploy Hetzner's CSI driver using Helm
  kubernetes.core.helm:
    binary_path: "{{ helm_binary_path }}"
    name: "csi-driver"
    chart_repo_url: "https://charts.hetzner.cloud"
    chart_ref: "hcloud-csi"
    chart_version: "2.6.0"
    release_namespace: "kube-system"
    state: present
    wait: yes
    values:
      controller:
        hcloudToken:
          value: "{{ hcloud_api_token }}"

- name: Deploy metrics-server using Helm
  kubernetes.core.helm:
    binary_path: "{{ helm_binary_path }}"
    name: "metrics-server"
    chart_repo_url: "https://kubernetes-sigs.github.io/metrics-server"
    chart_ref: "metrics-server"
    chart_version: "3.12.1"
    release_namespace: "kube-system"
    state: present
    wait: yes