apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "camel-karavan.fullname" . }}
  labels:
    {{- include "camel-karavan.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "camel-karavan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "camel-karavan.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "camel-karavan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: "KARAVAN_ENVIRONMENT"
              value: {{ .Values.karavan.environment | quote }}
            - name: "KARAVAN_CONTAINER_STATUS_INTERVAL"
              value: {{ .Values.karavan.containerStatusRefreshInterval | quote }}
            - name: "KARAVAN_CONTAINER_STATISTICS_INTERVAL"
              value: {{ .Values.karavan.containerStatisticsRefreshInterval | quote }}
            - name: "KARAVAN_CAMEL_STATUS_INTERVAL"
              value: {{ .Values.karavan.camelStatusRefreshInterval | quote }}
            - name: "KARAVAN_DEVMODE_IMAGE"
              value: "ghcr.io/apache/camel-karavan-devmode:4.4.1"          
            - name: "karavan.git.repository"
              valueFrom:
                secretKeyRef:
                  key: "karavan.git.repository"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.git.username"
              valueFrom:
                secretKeyRef:
                  key: "karavan.git.username"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.git.password"
              valueFrom:
                secretKeyRef:
                  key: "karavan.git.password"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.git.branch"
              valueFrom:
                secretKeyRef:
                  key: "karavan.git.branch"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.keycloak.url"
              valueFrom:
                secretKeyRef:
                  key: "karavan.keycloak.url"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.keycloak.realm"
              valueFrom:
                secretKeyRef:
                  key: "karavan.keycloak.realm"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.keycloak.frontend.clientId"
              valueFrom:
                secretKeyRef:
                  key: "karavan.keycloak.frontend.clientId"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.keycloak.backend.clientId"
              valueFrom:
                secretKeyRef:
                  key: "karavan.keycloak.backend.clientId"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "karavan.keycloak.backend.secret"
              valueFrom:
                secretKeyRef:
                  key: "karavan.keycloak.backend.secret"
                  name: {{ .Values.karavan.secretName | quote }}
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  apiVersion: ""
                  fieldPath: "metadata.namespace"

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
