- name: Install cronie package
  dnf:
    name: cronie
    state: present
  tags:
    - nginx
    - certbot
    
- name: Install certbot
  pip:
    name:
      - certbot
      - certbot-nginx
    executable: pip3
  tags:
    - nginx
    - certbot

- name: Register certbot
  shell: |
    certbot -n register --agree-tos --email me@domain.example
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered
  tags:
    - nginx
    - certbot

- name: Setup cronjob for renewal
  cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
    minute: "0"
    hour: "14"
  tags:
    - nginx
    - certbot

- name: Get certificate
  command: '/usr/local/bin/certbot -n --nginx certonly -d {{ inventory_hostname  }}'
  args:
    creates: '/etc/letsencrypt/live/{{ inventory_hostname  }}'
  ignore_errors: true
  tags:
    - nginx
    - certbot