- name: Generate a Let's Encrypt certificate
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_account_key_path }}"
    account_email: "{{ letsencrypt_account_email }}"
    challenge: http-01
    terms_agreed: yes
    subject_alt_name:
      - "DNS:{{ inventory_hostname }}"
