- name: Generate a Let's Encrypt certificate
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_account_key_path }}"
    account_email: "{{ letsencrypt_account_email }}"
    challenge: http-01
    terms_agreed: yes
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    subject_alt_name:
      - "DNS:{{ inventory_hostname }}"
    dest: "/etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem"
    fullchain_dest: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"      
