- name: Install cronie
  dnf:
    name: cronie
    state: present
  tags:
    - nginx
    - certbot

- name: Install nginx
  dnf:
    name: nginx
    state: present
  tags:
    - nginx
    - certbot

- name: Install pip
  dnf:
    name: python3-pip
    state: present
  tags:
    - nginx
    - certbot

- name: Install certbot
  pip:
    name:
      - certbot
      - certbot-nginx
    executable: pip3
  tags:
    - nginx
    - certbot

- name: Setup cronjob for renewal
  cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
    minute: "0"
    hour: "14"
  tags:
    - nginx
    - certbot

- name: Get certificate
  command: '/usr/local/bin/certbot -n --nginx certonly --agree-tos --email {{ letsencrypt_account_email }} -d {{ inventory_hostname  }}'
  tags:
    - nginx
    - certbot