- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Install KeyCloak
  community.kubernetes.helm:
    name: keycloak
    chart_ref: bitnami/keycloak
    version: 18.4.0
    namespace: keycloak
    values:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          # TODO needs to come from a variable
          - host: "keycloak.spoletum.net"
            paths:
              - path: /
    state: present
    wait: yes
    timeout: 300
    recreate_pods: yes
    update_dependencies: yes