---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-camel-k-playground
  namespace: argocd
spec:
  encryptedData:
    password: AgACmX10JJFMNq36xH91oiOBwzRE5z8f6EBkMZobZuH2zjiEmrS6gsjcv5m2yl/qykB2xqlRrdSZ2ZNetvq2ySPu1GmiQCNVL9sFqmMmCtiHH6p1AG9pT5NvPUYR7gpmAExrhUVDb3PBvtEQdI5EMo+7vEBNMfogJl4VO+r7lQblHg0q1CjEdNCdfV+6LoqsghswWbsLbn8K9zzZOM/9irARUe55k5/qhw2TP3mB5ieJ8H3XChL+GVXYlPG9hDmVQA+mDPVY/U1xK04kItADBFAlbwYfcWwwi21UCQv99KDxrpaKl7aIH/KKDZgTlLAquckrstcYXMx5buiv0xxhQNgGVKdlvYWiR4YNEnUuAeieKaCw2hJqXyd67Si8Wu6kF+szLp7jtEfhzlJo8umbAkjJmFHricxbtCBmljuzpZsD/UJRkkU1zUacz5JIIqkVRldLG2DMr5Kb+NYIr5Xf+k2pt+b+JsYclkvNp5gel1a53n8EtOtaK37OS0VX/Ggp7KBQog1LcmAexky74WR7oSgi/vHZt8330vd7e84JFh0kjqPpp3zaLuLUIU0v0da8YaC/gX/Y/kFRHws0/p7ZYzzzpzBQSUnPKn5vfY/VtWzblLHUJ9s2it+NeB/Z8od4A+5V5apjmJBa5449l+O/waBnrXIF/7909CuGY5Sh3/gQTD5/DXcwjVj/gcROHXV9gtjhn+TMT+eKmYF9cr4ekKITQwdcfNrCPBPRxTFh+oKM7Mq8iTF0L0/4
    project: AgC/bBnzWppzxJgkPzKJk4xJXnmLtigIona0pcvWY3dQ9/EHpNHS5Rl+FyZJRYtWH17VywGDY5oQ44THt9Ns1UavnZjGTSld1uyQPVbEf0DZhybwHCfcIXeU2WH6YHbccL8sHKxcLJvwZFU+pF1sTFSkK0zgEstGD9bzX70shHL8iwa6uNkF8kBhkYexftRPtbnb5Hg7icFE+KUENWWptsSqh+aVqcX4CWg/+KFSSyve0YeUbpAeCkHrwiYoqBZTP+qIMaegvJQgIZpX1oCoxyKxkjZ7EOMyo52dKcLU2hkhaHyjjJZvQM/YCl0l9yOIaAwr3tzpOWiJDuWP9y+4oyynaGXaMCMvLn261mgGbwdcIBjpzN7jPAtMM0XwO6cYZCgsFTTqlf9b8ZNTToLdmULztjJBWTXBAO9RqqzXEkMJ/uQK4mDuncMB8k8sH7K1DgrmaifwB2W16s96J5IHVFi3Utw6L6HAlrVs6BtYQxSN+bEgbKdTGk8m1BnRfDVASYiN5ztd4/vX64rZ3/lqWpaIBMklhnT/wSzqhggKICgm1x9xGWMFzkS3Bf2bdpPDOnPOBl42vp0y5Iyi7I3KsGgR5ggRneWJz27neSY49vc01pjho7N48DAELSBpqlrnJxEI6eiUkXNhdJfkdta/2MWM1xxh0y9zA8JLMLiVWSP576lu7z4sVeRuwt0q7Yb7Zq+EkFTT2z7C
    type: AgA0JQiLzhidlqeIB7AAYofZuhR6+IA872orZyeJiGjmzuL8Q1opvtlmHqijAeokr+FpI5LbLbMKQQFEvkPFji3pszHFxzeSxgTfMmFUv7pDnSgaBkURR+JgakTrtX9rhkD1SLwE8fAMfmB+QQ3tue2LV5Jf0FN/kNMiSymO3WHjtqYlwhwxGeD7BeA96+IjmY1YJ1RNUJq6SqqMko6eQV3T37Q0V+q4OTkNwXQyqHXWRm/vvzSbTmSCAm9gtCp5BDKes60OQWGARTgDrDIMJMusK4Q+CukmwvW5kD2kuGJHxdIsTTsHusz/jugyhY54jf7QJjg6rtyvbv0NJwIvLxBVsKZMWkC5sA4P3EG9yl6Qmhxc0uifOYXdN8Jbyh1Xu4bNf1p2a1lC3keIepztIl3ikldTxf4euNqiy9SBb6OSl4YI6hkHeHLLAGSIBRdSRTKAFAycDEBHevRpCof74E963Qrpp4Un1Tu6ynFPZmjg/IjUNar+5nGBV/BJW+74/GbXj6KtLV2Bs3lfQ+dLFXdM1gqQP2+IAEnw6rIa6e99meE9YuKPdeVT2FjT6QFkb9pO2AQFUDRDzZn1i+cRqod1/9ViKNKdAg9AHgLvP3i2ynBL3k4EiaFtZkS3gHFuvfJStbRQwCjbr7uDS9jfwuOFLZ/vaZ9u4AM6/Lp/KXnEYmTHjBjZIy8lW6je8FsNuPAqGxE=
    url: AgCTQU61wR1nIap4XrCaz2M+qlWF4vxnoL0+5znUrshKpWq3aFoQOyoK+bq7NRteZ7a/tmhWCtSOq5RWacM3TSBDRa9IoQaUpFSV8ez3opcHX214+b5BzLdGt3Nt8TMWYMDMQhctNySadZopYuZbzPcuyj7WbalqquEtPFVcdxfzP3rxwyq22J0I2fkMXS8JmN7xfgdTLk8xZwa/Y/5N3xj1U1RIvoHA/0xqlMX0A7g8Ljq+f/krdXOH3xxcjStCmqJM/pPYAPUkzMqRueYCS26ddhn0O/N3hsFcvbqbqTVBjNrsELWHYYbuPYk60SImVcPx0bkXrdxWlqre8BfpsEO5UmZIft5JCa6U/eHu/eKHSl23g8o/ye4bG8Wa5TFoT288NsjQDU6jY130dYAySrhlCqtwkurxr6AwfPS2lj07g64EMB47xNB9gVxXac4i5lg03OGk4V12Jrn+VNnYfzSIo7iJE8SZOTnWvKYr8q6wanL3yJyC8pdfZkfGXrgkuE1XktXO49j14lC92ruExP6q9h5ZSw1doNr9BkygcFopM22tMZQQEaEUuGben3/NL8msG0FELIlyIxavhDX5eOwuQUm1Le6ZVgoixKqUTyvF0W5hYH0v9QW70RW24DgadluCn1pWyoDwcVddt5aYZQl2ybpziZd+etnmu2ssSh8SriFfjtGI8b7YvwH2BLjqJ3L4II/4UjKWx9paQ6BcfKIPTrCkGfupGZMnfwXyC6r4R1lLSmmW8pZ/fGLosMcK
    username: AgBUO2Rw2xQhHHbI9xvcyVCweeJ3KNIxMf6z/LRPYRX9FExR0uYEvegDp8F1xOHzlRUUcPmZe4hc8FnucuGusM2LE2oVs+DZ8mMkT9OERId/WuyLkFYfjieATE4yVvlP73CC2jHJZ/KWDPnA3K8J3y4fGoTbEn1MzGPY3L04Y5iUNksrspEyGW+XsiaT438i11TMC3TCHYc5JL1uiY0MYZ2/nQWrbOBSt/aP4LW2Gor02oeoAxnkslfmowxeeAhTyg6R2dA73uTTounh5+oG4rr9VpXdd+MPFsMeS9MLQBBpLvuWGsrwGpj5tXJyZAIV48DGlio2ItZ6UEAluyQzXHNVau4p4WDHdTny07rl0GYdltxPVLZa7lWMmyjXOF91OaiUVhCMm5C85+H3KpCI9am3fTp29Yg82+D3PpT37U/V0/wRQsN9e7UMXzGfNeck+7sc8TWt1z9nlCn+Xv7Oiifd6fjoZn3MiNGJyMUP02jwp8WweaGZZqsRUfTYDtikcIF9s1kaUIpiC8peZEpy4R15wZ80W1lLasJvZvcLoxU9iCMDn1oC7LSwEJ89nujioID5rnLhseFcKsAPUrLjBrSoS3WiwN5QaxMvMUmtj1y6ISKcdERLpAVGIqe5gX3sE2zcY/u6thmmscPyZdtvtv+hBdVvTnhSanSNfMTHJ1pauTFSl8Uv37ztnM5hdgnCTjacQrFnfrC4Zw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: github-camel-k-playground
      namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: camel-k-playground
spec:
    destination:
        namespace: camel-k
        server: https://kubernetes.default.svc
    source:
        repoURL: https://github.com/spoletum/camel-k-playground
        path: .
        targetRevision: HEAD
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
        retry:
            limit: -1
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m