---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-camel-k-playground
  namespace: argocd
spec:
  encryptedData:
    password: AgCCBamTQDvTtyRR38mLBZY5PlqHhO7k6qNWpMVwdk4H7vBK8Do2qteaqf9xnLrKsouc2V0Dx3IQex8Q/+qQDnHPhGWR2Rcql647IBQJjEY1kVQYV92i8gJJ/6YMSfJgzjjUqErhAd6UzY/zSTkaC5YlUCJRBe/ZobPOmezJW9QKagcdurpBCXOA252vRNc6eLXmGJVMEDi8TP3OhU3uPYEN/ozQGuLZZky2CC7RLRvPO6+eITEetruLjGPCVnXk1q7Gz8aU/pFLciWqFAPwfHClEHLBZmrNLJ5/r9iwTxZLlmKELzzL8nMocKQRSq7acKG0KykoS/dhyBwETn30qxKvAKm4WqfnJ5zqZCT1XbZWRROFYTxfZU+1t6A/5hKiqzSCsDq/kThkQasw3LaM5qCJT9d4HqF61ggxgqf/r5mvSie8W28Zztdtd195Rxf0Z4XBB3buEmohRr/zPaF88uv9sXtTS84e8tu/LbM9OS4rG5OFoH4aXDX4S6aEFqC+4em0w1xzkVjQfIa4KYmQ+jbd3pDfuWlpdEv5KkIAeadcI52eaydlNuuNREvqTtd5QJ/p7IYNs0VP2/gN+wl308j6dB2UTy+L5o+Ec8mgPvmV0SBjq/9sRWwUUcwyAIzm8m/TaMKLqa8MwUe9eZcRG1LQ/S8Q7aWAsf0bcMcgRp/p5c5cQIAzIyYbsEduiTNbhT+R0CSt6P2pxaPl+4ln3TbwEdzLToQgG8ZBQM/jg8oEO81eyYchz/jv
    project: AgAKmZyeljaHeEvFceSLOh6tQOSDELED1pYtKejrj/Nqo96l0HTW3WQkbuGpYgJZAOk8/f3Vm862IY/IjueCD17Gn8Pzp/IFPdtwhOW1GzMlNvdAdkHU+m7vOxzwdIUUBakgEKZz50JFPq5FOpNlk7ljBxfMrOh8Dgw+ZI4fVf99jI09sa/BIdD6i5u0cUIAOee9Jx85Lw76WR7FJH6Q6iEd8gUI6M+0a5NLKus/glsnD+oeHMwu7bX96X2jsEdSv5mrTv9QIFsVoGsMD2aaPxQuUTfbTAT4FU/Ou4eP5G0oehoLD6Y1NvLHyFrpspu+oN8mQQeQdE7+hgIK+tEmbF5kH6P5JcRe+zH46692ozYsaqeLmzYkzwRBah81/lkmCuuu2zHphVkReF103jpqY8Fv8dA4B+piTX8mvXqzE0bgVe51zfn5r10Q9IFz8TG1CEl90ejAUL8u+PIWvoFTYzgvy9776j7uvSdds85UPb8LVqbCxvSc4yHQO0Mt9uzdtzQzGqVYeJ0OiNkcDA7Nm0WhVKNEthdkl33/SYFobRXMs+d+13yapPrGERPX9qBaXDlfdFr2iZikXV1hz0oxTdnGzaejepU5cAAArzTbpxDn89rrul2r2Wz0KbPgVjzBJcXyXzSrMEUrNfU2IhTTBxq77gcxvIg5HCX7Csxe45kukU3EXlPhpSqzsuieOb3/s1q04ToyeZkp
    type: AgADsYirAy+dJ54Xa7EcQbdhKp8V7x8HCuKjYoyUV45CthC/7MjDxEaru5j6Jgk522Lc7sZ5Vi1ysRPv3hPNqp2AyhANsThFoc+Kl5om6yjJne7cQeW+HbulSVMIgk7fH4NV7FlFPlV9egI78szJuoso4JXL4cldprL1cQ2/pnZpao0HFVqHs2LRs9N/kirqRPsAqAz0073TmB3FMMLepw5fuPMqawCNp4IHl2vqOtKISkRez9HB4ya2QjRbYewVa0cqd496qhmRkDudwMyP2gr1AatUnoAd6WVpU37yv7G6lIi7rNJX+IBHXF6E68Q5flGRueevC8iOQS+zD8ZxfXLAX+KA0cV/ZYyDEOv8gSUC5ZM4t72h90nexvBNHGXAwrAycTBdep+RrfgWxF21gTRprVdrfXdWZB9TWdG7ioPGE3V4TL3EqA/SdXZRgt/wH9PQYHRzyTnnDmEKqXCJfw60mjVd/BUe0JC1YSRwnM2v57oXlCvqznLdz/01fUsO3gTKcPSq9lBC7L+0tsSpOUgMTh6Ror3Z+jT4wsSmuM2xOA437deLS22wq0kMUeypmYzox8vXl3MAHomXby7zbthxE1vtDKNSeL2d+ZjsP/wmTY3kwoivE58lC8jgo6JxgIAMS0YiLM/Ohb2CkP3UD0BHkap9qntOZnWfWPdtyrzbQRG0vrZVxh8HgcCsw9RNmfbnhRk=
    url: AgCBgtwKy+CZeVC9yEQQikgk5n8AtaTZ4ISJ4NjSbLrgK3d5Tf2jB1OpSuwMo0jeYGEgq4Gz2u+a14kcuEWWVNBSnUME8PHv/KH+BaRiRtPmUMCqNYp8Jvk6DPA1t1X45xExj+QmFeXMZybSqQ1aKNahJK3UmUedOtt+18qLy5r7aizG6dKogXxxPyRo+sSIJt0cn9Ir33sEpncI+w8K/Sgj31GmTUfq5JSiQElDem24cM2/LWnfoYp1qDlxSd5NXGo1hnojrDACfEH9X7HDQPxhofwOH8Vsf7ISNB5dhgbuzXowXfed77epNk7o20oKuWo49Dvusjal7UhMG3LpJ+g/STnmHxUwvGD508gH0Vav1brdHaQZ/jmkQmONb/ycGW1jwI+sG7mFsUuzdxSna21ERSk317L254vhGV0lXUjE9mZKP8NtmN0w4RZo+kuQLRE5MxccCFZT7HXMHc493Kx6OAvpwL48ZM8+V+n+oOtRRR8gSMvm+PcydWYYfkfF3/xD1dL9y6FkY1odZ3/qJ862Hwc8bvK+XEFXHLWVR4PDdBOoP4YmVno9UQMXM51IkU+gF7nh684x5FaikcwrkX207tJVG9uXm5pOk0fHlNAGxxyh2d6gyaO/7JeijDN8C2xNKzEXedN6wblUKczkzFbuBy2tiTGccYMngIWunenguR8chG5wvW3+yV/SeFcILs+GMiSYWFBGFNDG5W49G6FJ4CBRURCrBKNCzgjryxTLjp0U5jxULnLMpVa0qK8J
    username: AgAjQEZqXTCWG7sfPqjY8VaFg09Gk68tVDaIWsZycmnN3hm8PnrmSt+ugIlpml67MTDqEOravSk5apYMOeJhaHCRZiiS/tD+ZQPIBe4N5fS/kwMXtl0S0xf3k26QjcMsva4RdCPWK/5jE9EiENI+eIfayR35QybmlAJZiPFcwBgFVx+zb9xT35/P767o+D418g++CZV7FZ/zB3iUwiuK57NvE0uZUaigKQQ6prhPeWcypSEXRoONZpw6nuDrUsNSBiiu1LhnSHeKNrBG1+pbH5mI3SBeUsyW/1/kj4qxzDXFGoFpGvSOubI8ywDCPZdmb4hMrHNMjPI312U4FVW1XX1aJQiNlQ2buQYWNcGURpY3kYU8O1gWFRixt418mEoDsV+nxJnvoB8VByMt9b9sYQiIvlRhd9GqMA2so1PcroFWfenBvMC8uqYpWeRBzvJfDyr+ZpfjVXBkPHmlxdpnOkjVdQNDBPNkpV8HCe6BV0NxEsiI/ORWT2f6zhgi4+ZekBi6ybtgxq97RBzCuf1vBXA68qRfSuI/Xy7+UI/m8WGGUKsricG9zWqgSZ3exkAUJYeAUm6ahsC/j5BQtJ/dCvCc5t+IP2xDl0QzxUe+CR2j4mZljVdhQ7igMfsCqFzz0aY68WPGLTT6Y5Dc6jeUwVpII6KGSaqLLQZWrUfrsNWqhM/G2OcDJVjyZWAYx+VUvFA92QewZGVPjw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: github-camel-k-playground
      namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: camel-k-playground
spec:
    destination:
        namespace: camel-k
        server: https://kubernetes.default.svc
    source:
        repoURL: https://github.com/spoletum/camel-k-playground
        path: .
        targetRevision: HEAD
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
        retry:
            limit: -1
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m