apiVersion: v2
name: karavan
description: Karavan is a web-based tool for building Apache Camel integrations.
version: 0.0.1

dependencies:
  - name: camel-karavan
    version: 0.0.1
    repository: file://../../../charts/camel-karavan