apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
version: 0.0.1

dependencies:
  - name: metrics-server
    version: 2.11.4
    repository: https://charts.helm.sh/stable