- name: Install k0s
  block:
  
    - name: Install the k0s binary
      command: "curl -sSLf https://get.k0s.sh | sudo sh"
      args:
        creates: /usr/local/bin/k0s

    - name: Create a single node k0s cluster
      command: "k0s install controller --single"
      args:
        creates: /etc/systemd/system/k0scontroller.service

    - name: Start and enable the k0scontroller service
      service:
        name: k0scontroller
        state: started
        enabled: yes