- name: Disable root login and ensure no conflicting settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  loop:
    - { regexp: "PermitRootLogin", line: "PermitRootLogin no", state: "present" }
    - { regexp: "PermitRootLogin prohibit-password", line: "", state: "absent" }
  notify: Restart sshd