- name: Create Hetzner infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create SSH key
      hetzner.hcloud.ssh_key:
        name: elysium-dev
        public_key: "{{ ssh_key }}"

    - name: Create network
      hetzner.hcloud.network:
        name: private
        ip_range: 10.0.0.0/16
        state: present

    - name: Create placement group
      hetzner.hcloud.placement_group:
        name: elysium-dev
        type: spread
        state: present

    - name: Create server
      hetzner.hcloud.server:
        name: elysium-dev
        image: ubuntu-22.04
        server_type: cax41
        ssh_keys:
          - elysium-dev
        placement_group: elysium-dev
        state: present
        user_data: |
          #cloud-config
          package_update: true
          packages:
            - curl
          users:
            - name: ansible
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLNTNsj1jbwXuco61alHD3hdpq1OoVEAFyqTpLmdhtJxXdsiHs4tyNFcgXbQK/gRcFsRiq4c9Vx8muNYhOfPqj2mQgO+MoSaz/G7UyndVhX2BVW8BpnOdua13vFRNlDeMkbRUq4hrf8UX7cdPj7edQPxTUIE0xONUCL6a+BClDWjyUYhUY1PaRgfxH3baaMnFsUG5f367wn6JytwBJ+927MvMDJtXQm+eTUwHtmKGMf2JfyKIKjNEKKi+0wPuDyRUASQHR8wBzfNX0AS7vPoKwO9e4OyOGLOoJyYMzqqOwJelyEuPWBNydxACY6cMUUfMlIvYJ8gPQP7dMMd50o8IDkutpNt9lvY1A100BsrlWCjBI1mutmOVvnNyHdMJJV2MKO8TPBd+DvAF9IRHDlpvjdyKNftMFB+D+2QkwzSCC84Nx8b9fjdU46rzWKsFweSIfWvaoeLOEKqbuf9LgDekQabPUBOhPCMcgSXWYKVrtzEw4a7aFfMTTV1KP78Zsr8k= alessandro@DESKTOP-CQI0QDA
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCV3CGG5V5iii6/KhRiFAie60f22IWTFvLoLWQztsDrVHxK68KhoxGnfIfDjI7iqj19HqaCCeCY/Sp/j/eZfpqC+/v/6xk6IQQXFZdx0LYG4Z0rsxwoBvCrxoXHcmU+tBEfoFZdKvhqBG+eoSxQOx5S1vtjENaDViln2cj4zpNpE/RkSoOLYC7aNoQwmIcr4G+yrzpCRWyCHdNAnq6qIy3EyWh/dibRrdp1F/1PH8NU12FvFgb+SmCt5CkN2MmMXNRnqW7P61PElVKwOA2jrg4JXub9o3Skd5BcCwxX7/uASvc49icp4EyC5/7wM9SeTGcvBqYFNP8kRdfXo0uPlsam8ecsXnpO0hHAkUe/67ovrt8JApEGngs+MuVWlFB/UCiWWooYLlX1CAQGNJMcyUDuT6TckxShErqPF2xRDCFoLBzH1TOYXKvNtRhw1/7CallylifbseQWq5FIUViaqcY4V8eEFxeDjDbmQA8R8vp7FN6TI1z8AlAkagXdhSFMpIM= alessandro@DESKTOP-CQI0QDA
      register: elysium_dev

    - name: Create DNS entry
      community.dns.hetzner_dns_record:
        zone_name: "spoletum.net"
        record: "spoletum.net"
        type: "A"
        value: "{{ elysium_dev.hcloud_server.ipv4_address }}"
        state: present
        hetzner_token: "{{ lookup('env', 'HCLOUD_DNS_TOKEN') }}"

- name: Configure Kubernetes controllers
  hosts: k8s_controllers
  become: true
  gather_facts: true

  tasks:
    - name: Install k0s
      # Install k0s by getting it from the internet as per instructions
      # https://docs.k0sproject.io/main/installation/
      ansible.builtin.command: 
        cmd: curl -sSLf https://get.k0s.sh | sudo sh
        creates: /usr/local/bin/k0s
