- name: Install TLS certificate
  hosts: public
  vars:
    letsencrypt_account_key_path: "{{ lookup('env', 'LE_ACCOUNT_KEY') }}"
    letsencrypt_account_email: "{{ lookup('env', 'LE_ACCOUNT_EMAIL') }}"
  roles:
    - letsencrypt