- name: Harden server configuration
  hosts: all
  roles:
    - hardened
  become: true

- name: Process publicly-facing servers
  hosts: public
  vars:
    letsencrypt_account_email: "{{ lookup('env', 'LE_ACCOUNT_EMAIL') }}"
  roles:
    - letsencrypt
  become: true

- name: Install PosgreSQL servers
  hosts: postgresql
  roles:
    - postgresql
  become: true