on: [push]

jobs:
  
  ansible:

    runs-on: self-hosted
    environment: development

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ansible
        run: pip3 install poetry ansible
          
      - name: Install Ansible Galaxy dependencies
        run: ansible-galaxy collection install hetzner.hcloud

      - name: Build the infrastructure
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_DNS_TOKEN: ${{ secrets.HCLOUD_DNS_TOKEN }}
        run: echo $ANSIBLE_VAULT_PASSWORD | ansible-playbook --vault-password-file=/dev/stdin -i inventories/elysium/dev/inventory.yml playbooks/elysium/dev/main.yml