on: [push]

jobs:
  
  terraform:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Generate inventory file
        run: terraform output -raw inventory > ../ansible/inventory.ini
        working-directory: terraform
  
      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Install Ansible plug-ins
        run: ansible-galaxy collection install community.crypto

      - name: Start SSH agent and load private key
        run: echo "${{ secrets.ANSIBLE_PRIVATE_KEY_CONTENT }}" > ansible.pem && chmod 400 ansible.pem
        working-directory: ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini -e 'ansible_ssh_private_key_file=ansible.pem' playbook.yml
        env:
          LE_ACCOUNT_EMAIL: ${{ secrets.LE_ACCOUNT_EMAIL }}
        working-directory: ansible