name: Pilum Terraforming

on:
  push:
    paths:
      - 'terraform/envs/development/**'

jobs:
  
  terraform:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      AWS_DEFAULT_REGION: eu-south-2
    defaults:
      run:
        working-directory: terraform/envs/development

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve terraform.tfplan
